### PR TITLE
*WIP* Ubuntu 16.04 readiness

### PR DESCRIPTION
**Pull request by alanorth**
**Work in progress, do not merge!**

Beginning to get the playbooks ready for Ubuntu 16.04. Most of the work was already done when we started testing 15.04 as the first post-14.04 Ubuntu release. My goal here is really to get enough of the playbooks ready so that I can start testing DSpace on an Ubuntu 16.04 stack, so I will aim to fix the bare minimum of the common stuff. ;)

So far I've done successful runs of the following tags:
- [x] packages
- [x] firewall
- [x] sshd
- [x] sysctl
- [x] rclocal
- [x] udev
- [x] sudoers
- [x] raid-monitoring
- [x] backups
- [x] java
- [x] nginx
- [x] postgres

### CODE REVIEW

**Comment by oguya** [comment]
w00t! :+1: 
Doing some tests too over here using the daily builds

**Comment by alanorth** [comment]
I don't wanna take away your fire, broheim, I just wanted to kick the tires on my DSpace ish, ya know? :)

**Comment by oguya** [comment]
ha! Don't forget we need to also be ready for Ansible 2.0
https://docs.ansible.com/ansible/porting_guide_2.0.html

**Comment by alanorth** [comment]
Oooh, I hadn't seen the 2.0 porting guide, thanks. I figured that my and our stuff worked in 2.0 so it was fine, but there are probably some old conventions buried in there. Ok, I'll keep going on the 16.04 stuff and you drink some coffee and hack the 2.0 stuff. ;)

**Comment by alanorth** [comment]
Tweaked PGDG sources.list to use Ubuntu 15.10 (wily) builds on Ubuntu 16.04 (xenial) hosts, installs fine but haven't tested anything more than that. I'll do a full DSpace install and test some workflows after the whole playbook stack works on Ubuntu 16.04.

**Comment by oguya** [comment]
No need to revert e0118cc3b4c2e5acfa476b67874c7ae6f274ed8d because it's already taken care of by eac4ce818c5e065b5cae91c40712960a511c2a75. Maybe I'll just cherrypick it to `ubuntu-1604` branch.

**Comment by oguya** [comment]
Damn it! Actually eac4ce818c5e065b5cae91c40712960a511c2a75 modifies `roles/dspace/templates/nginx_org_packages_ubuntu.list.j2` and also `group_vars/dspace`. So no go on that cherrypick...hmmmm :confused:

**Comment by alanorth** [comment]
Also, we can use Xenial builds for Postgres now:

http://apt.postgresql.org/pub/repos/apt/dists/xenial-pgdg/

The `ubuntu-1604` branch just needs to be rebased on top of master since lots of stuff has changed with nginx and dspace. No biggie, and no rush since we don't have any 16.04 hosts yet.

**Comment by alanorth** [comment]
Rebased on top of master for all the nginx churn above. This should be good to go now. Testing would be good to see if it breaks any of our current Ubuntu 14.04 stuff, rather than if it breaks our non-existent 16.04 stuff, though.

**Pull request merged**
